### ISSUE TITLE
Search ignores `--from` and `--to` arguments and always returns most recent log entries

### ISSUE THREAD

**Issue by dtran320** [logdna/logdna-cli#10]
## Steps to reproduce:

Search using `--from` or `--to` (or `-t` or `-f`).
```
logdna search --from 1501617600 --to 1501629000 -n 10 'acknowledged'                                                                                                                                
search finished: 10 line(s). hosts: all. apps: all. levels: -debug. query: acknowledged
Aug 02 11:00:14 <redacted>
Aug 02 11:00:14 <redacted>
Aug 02 11:00:14 <redacted>
Aug 02 11:00:14 <redacted>
Aug 02 11:00:14 <redacted>
Aug 02 11:00:14 <redacted>
Aug 02 11:00:14 <redacted>
Aug 02 11:00:14 <redacted>
Aug 02 11:00:14 <redacted>
Aug 02 11:00:07 <redacted>
```

**Expected behavior:** Search returns 10 log entries matching the query "acknowledged" during the specified time interval, August 1, 2017 8:00:00 PM to August 1, 2017 11:10:00 PM

**Observed behavior:** Search always appears to return most recent logs available matching the query.

**Comment by dtran320** [comment]
Looks like adding `--prefer-head` gets the output that we would expect. If that's the intended behavior, that's definitely not clear from the help text:
```
  Usage: search [options] [query]

  Limited search functionality with optional filtering (beta). See 'logdna search --help'

  Options:

    -h, --help             output usage information
    -d, --debug            Show debug level messages. Filtered by default
    -h, --hosts <hosts>    Filter on hosts (separate by comma)
    -a, --apps <apps>      Filter on apps (separate by comma)
    -l, --levels <levels>  Filter on levels (separate by comma)
    -n, --number <number>  Set how many lines to request
    --prefer-head          Get lines from the beginning of the interval rather than the end
    --next                 Get next chunk of lines (after last search). This is a convenience wrapper around the --from and --to parameters.
    -f, --from <from>      Unix timestamp of beginning of search timeframe.
    -t, --to <to>          Unix timestamp of end of search timeframe.```

**Comment by baronomasia** [comment]
@dtran320 Good to hear from you! Our CLI still needs a bit more love, and this is definitely one of those quality of life improvements that will make our CLI much more enjoyable to use. I'll make sure our engineers that work on the agent review your feedback and incorporate it into future improvements made to the CLI. I can also reach out once additional changes have been made if you're interested. Hope all is well over at UpbeatPR!

**Comment by smusali** [comment]
This PR (#21) handles it too.

**Comment by smusali** [comment]
It's fixed and updated!
