### ISSUE TITLE
--number 1 returns 0 lines

### ISSUE THREAD

**Issue by cameronbraid** [logdna/logdna-cli#11]
$ logdna search  -n 2
search finished: 2 line(s). hosts: all. apps: all. levels: -debug. query: none
Aug 23 12:06:12 ...
Aug 23 12:06:13 ...

$ logdna search  -n 1
search finished: undefined line(s). hosts: all. apps: all. levels: -debug. query: none
Query returned no lines.

**Comment by jakedipity** [comment]
This issue has been resolved in pull request #23. Closing for now
