### ISSUE TITLE
Search returns nothing, even if the data is there

### ISSUE THREAD

**Issue by croqaz** [logdna/logdna-cli#14]
> logdna search -l info,warn,error -n 25 -a myapp
 search finished: 0 line(s). hosts: all. apps: spartan. levels: info,warn,error. query: none
 Query returned no lines.

> http GET https://api.logdna.com/v1/export from=="$(($(date +%s)-86400))" size==25 apps==myapp authorization:"Basic XXX"

> logdna --version
1.2.2

This returns the data.

Note: The data cannot be seen in the Web Dashboard!!

**Comment by croqaz** [comment]
Update: It's because of the META.
I'm sending the data from the Python lib, using:

> log.info("Blah blah", {'index_meta': True, 'meta': {'whatever': 'yes'}}

All the logs get destroyed ...

**Comment by smusali** [comment]
@croqaz , can you confirm whether it is still an issue?

**Comment by smusali** [comment]
Since it was tested in #21 and proven that it works well, I am closing this issue!
