### ISSUE TITLE
Search sends wrong query param for query

### ISSUE THREAD

**Issue by rhart** [logdna/logdna-cli#15]
The query supplied with a `search` command is ignored and all lines returned.  I think this is because the wrong query param is being set.

The documentation (https://docs.logdna.com/docs/v1-export-api) specifies that it should be `query`, but I believe it is being sent as `q` https://github.com/logdna/logdna-cli/blob/master/index.js#L314

**Comment by stuckj** [comment]
Yep, this definitely looks wrong. Kinda makes the search feature of the CLI not at all useful.

**Comment by smusali** [comment]
Thanks, @stuckj! You Pull Request was already merged on May 29th.
