### ISSUE TITLE
Command tail functionality broken since last update

### ISSUE THREAD

**Issue by schans** [logdna/logdna-cli#19]
Hi,

The command line tool does not seem to be updated to match the latest update.  Log lines are no longer parsed correct and look like the following:

Aug 17 12:44:36 myserver.lan sshd  info  <38>0 2018-08-17T10:44:36.744092+00:00 myserver.lan sshd 14358 - [logdna@48950 key="XXXXXXXX"]  Connection from 123.123.123.3 port 45399 on 123.123.111.3 port 22

It looks like the raw message is printed instead of a parsed one make the messages hard to read. Also from a security pov it is unwanted that the api key gets printed.

Thanks
Bart

**Comment by smusali** [comment]
Explained [here](https://github.com/logdna/logdna-cli/pull/20#issuecomment-435479735).
