### ISSUE TITLE
lodash removal incomplete, fails npm test

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [logdna/logdna-cli#26]
As of 2796ad2, there's one remaining attempt to use `lodash`, which has been removed: https://github.com/logdna/logdna-cli/blob/master/lib/utils.js#L77

**Comment by smusali** [comment]
Hey @mgabeler-lee-6rs, thanks for reporting!

It's fixed now with [this commit](https://github.com/logdna/logdna-cli/commit/f92f57bb8f107085db80771609297797c5e77523).

**Comment by mgabeler-lee-6rs** [comment]
:metal: thanks!
