### ISSUE TITLE
SSOLogin Broken

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [logdna/logdna-cli#29]
With the latest updates, if I try to use ssologin, the CLI just hangs -- whatever polling its doing to verify if the token is valid never seems to succeed.  The browser step shows no signs of issues.

I verified the older 1.2.3 version can still authenticate.

**Comment by smusali** [comment]
@mgabeler-lee-6rs, found the issue and fixed - gonna push the changes asap!

**Comment by jesse-localz** [comment]
I'm still seeing this issue unfortunately :(

**Comment by smusali** [comment]
@mgabeler-lee-6rs, @jesse-localz, just wanna make sure you're still seeing the same issue in the current version

**Comment by mgabeler-lee-6rs** [comment]
Installing the latest debian package using the instructions in the READM still delivers version 1.2.3, and there are no linux packages in the releases page for newer versions, so ... not verifiable at this time.

FWIW, I also don't use the CLI any more, as I've found it unsuitable to my needs, though this ticket is not the place to go into that :)

**Comment by andkon** [comment]
@mgabeler-lee-6rs if you've got feedback about the CLI I'd love to hear it! I'm the product manager on integrations. Just throw me an email (andrew.konoff@logdna.com) or book a call here: https://calendly.com/andrew-logdna/user-interview

**Comment by smusali** [comment]
@mgabeler-lee-6rs, thanks a lot for your feedback on CLI you shared with us! We have recently released `v2` containing `SSOLogin` fix as well.

Please, let us know if you have any additional comments!
