### ISSUE TITLE
Feature request: Manage LogDNA from CLI

### ISSUE THREAD

**Issue by matthagenbuch** [logdna/logdna-cli#34]
As a developer and DevOps engineer, I'd like to be able to automate the configuration of LogDNA boards, views, and alerts from the CLI.  This would enable my organization to deploy the same LogDNA console to multiple environments rather than manually configuring each LogDNA instance to be consistent.

**Comment by Nashluffy** [comment]
@andkon actually seems like my issue was a duplicate in this repo. Last touched on 8 months ago?

**Comment by andkon** [comment]
@Nashluffy good eye – this way before my time! Looks like we have this tracked already on our end too. Hoping to bump it up to next quarter.

**Comment by andkon** [comment]
Closing in favour of #41 .
