### ISSUE TITLE
grunt linux is trying to use nexe

### ISSUE THREAD

**Issue by dpnova** [logdna/logdna-cli#6]
Installed and run like this:

```
git clone git@github.com:logdna/logdna-cli.git
cd logdna-cli
npm install
sudo npm install -g grunt
grunt linux
```

Output from `grunt linux`

```
 INSERT  dpn  ~  workspace  logdna-cli  grunt linux                                                                                                             3   master 
Running "lineremover:nukebrowser" (lineremover) task
✔ node_modules/ws/package.json (removed 0 lines)

Running "exec:nexe" (exec) task
>> /bin/sh: nexe: command not found
>> Exited with code: 127.
Warning: Task "exec:nexe" failed. Use --force to continue.

Aborted due to warnings.
```

**Comment by leeliu** [comment]
Yup, that is what should happen. The command basically builds a Linux binary and packages it as a rpm/deb. Were you looking to do something else?

**Comment by dpnova** [comment]
The readme says nexe is only needed for Windows.

Is it possible to run the cli without building anything? I'm on gentoo..
Seems like it should just run as a script?

Am 16.11.2016 4:24 nachm. schrieb "Lee Liu" <notifications@github.com>:

**Comment by leeliu** [comment]
Oh! Thanks for pointing that out. It's definitely needed for both. We'll fix that.

You can just run `node index` in the folder. We do have a prebuilt Linux binary at http://repo.logdna.com/linux/logdna.gz though I'm not entirely sure if it'll run on gentoo.
