### ISSUE TITLE
logdna tail : `-h` is used as the short form for two different command flags

### ISSUE THREAD

**Issue by viktorbenei** [logdna/logdna-cli#7]
`-h` is used as the short form of `--help` as well as `--hosts`.

Right now if you call `logdna tail -h` (to get the help text) you'll get:

```
  error: option `-h, --hosts <hosts>' argument missing
```

**Comment by leeliu** [comment]
Yeah, you'll need to use --help for that particular command. We use the `commander` module for this and it's a bit confusing but there's no way to change the output afaik.
