### ISSUE TITLE
Can't get search to work

### ISSUE THREAD

**Issue by leshik** [logdna/logdna-cli#8]
Whenever I type, even an example from docs, I always get `Error 404: {"error":"No Resource Found","code":"BadRequest","status":"error"}`.

BTW, is it possible to dump N lines of logs, like `tail -n 1000`?

**Comment by leeliu** [comment]
Hey leshik, apologies. We're in the middle of doing a release with the new endpoints for search. It's just taking a bit longer than usual. Let me see if we can restore the old endpoint temporarily for now.

**Comment by leeliu** [comment]
Alright, it's back up. The old search is not very good...once the new release is up, it'll use the export api instead.

**Comment by leshik** [comment]
Awesome, now it works!
Does any way exist to output more than 150 lines (or search between dates)?
