### ISSUE TITLE
Filter for groups in tail command

### ISSUE THREAD

**Issue by caarlos0** [logdna/logdna-cli#9]
`logdna tail` supports only hosts and apps, would be nice if we could also filter by group :)

**Comment by eugene-soxhub** [comment]
You can sort of filter by groups. If you select a group in the dashboard/web UI, you can see that there is a query param called `hosts`. If you URL decode the value of that query param, you can pass that as the param to your `logdna tail -h ` command

**Comment by leeliu** [comment]
@caarlos0 Alright, try this now: `logdna tail -h g::groupid`. You can get groupids from the web UI by selecting a group and looking at the URL (I know, not the best UX...need to get this to work with the group name eventually).

**Comment by leeliu** [comment]
Works with `-a` as well for apps
